# Generated by Django 5.0.1 on 2024-02-20 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_rename_nomination_note_header"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="count_view",
            field=models.IntegerField(default=0,
                                      verbose_name="количество просмотров"),
        ),
    ]
