# Generated by Django 5.0.1 on 2024-02-05 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                                           primary_key=True,
                                           serialize=False,
                                           verbose_name='ID')),
                ('nomination', models.CharField(max_length=150,
                                                verbose_name='наименование')),
                ('description', models.CharField(max_length=150,
                                                 verbose_name='описание')),
            ],

            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                                           primary_key=True, serialize=False,
                                           verbose_name='ID')),
                ('nomination', models.CharField(max_length=150,
                                                verbose_name='наименование')),
                ('description', models.TextField(verbose_name='описание')),
                ('imagine_url',
                 models.ImageField(blank=True, null=True,
                                   upload_to='products/',
                                   verbose_name='изображение')),
                ('price', models.DecimalField(decimal_places=3,
                                              max_digits=10)),
                ('created_at',
                 models.DateTimeField(auto_now_add=True,
                                      verbose_name='дата создания')),
                ('updated_at',
                 models.DateTimeField(auto_now=True,
                                      verbose_name='дата изменения')),
                ('category',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   to='catalog.category')),
            ],
            options={
                'verbose_name': 'продукт',
                'verbose_name_plural': 'продукты',
            },
        ),
    ]
