# Generated by Django 5.0.1 on 2024-03-06 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_version_is_current'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='number',
            field=models.IntegerField(verbose_name='номер версии'),
        ),
    ]
