# Generated by Django 4.2 on 2024-03-18 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_product_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_published",
            field=models.BooleanField(default=False,
                                      verbose_name="признак публикации"),
        ),
    ]
